### ISSUE TITLE
Consider blacklisting "added"

### ISSUE THREAD

**Issue by orhun** [crate-ci/imperative#50]
Hey,

I'm coming from the `committed` tool and something I come across often is the use of this commit message format:

```
test(xyz): added ...
```

Whereas it should be:

```
test(xyz): add ...
```

Blacklisting "added" would solve this issue and `committed` can catch these commit messages and warn the user about this.

**Comment by epage** [comment]
I would assume "add" is the root for "added" but rust-stemmer says "ad".  This seems wrong to me so I opened an issue upstream in snowball: snowballstem/snowball#182

I'm tempted to just add a quick bypass for now for this one case.

**Comment by orhun** [comment]
Just tested the latest version of `committed` and using "added" results in a warning as expected now, thanks!
